{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.frontend.name }}
    tier: frontend
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  sessionAffinity: {{ .Values.frontend.service.sessionAffinity }}
  {{- if eq .Values.frontend.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.frontend.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  {{- end }}
{{- end }}
