{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.backend.name }}
    tier: backend
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
  sessionAffinity: {{ .Values.backend.service.sessionAffinity }}
{{- end }}
