# [Task T024] Dapr Secret Store component for Kubernetes Secrets

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: vaultValueType
    value: "map"
  - name: defaultNamespace
    value: "todo-app"

scopes:
- todo-backend
- todo-recurring-service
- todo-notification-service
